name: python-${PROJECT_NAME}
version: '3.6.4' 
summary: python 3.6.4 built from source
description: |
  just built from source!

grade: stable
confinement: classic

parts:
  python:
    plugin: autotools
    source: https://github.com/python/cpython.git
    source-tag: v3.6.4
    install: |
      sed -i 's|/bin/python3.6|/usr/bin/env python3.6|g' $SNAPCRAFT_PART_INSTALL/bin/pip3
      sed -i 's|/bin/python3.6|/usr/bin/env python3.6|g' $SNAPCRAFT_PART_INSTALL/bin/pydoc3
      sed -i 's|/bin/python3.6|/usr/bin/env python3.6|g' $SNAPCRAFT_PART_INSTALL/bin/pyvenv
      sed -i 's|/bin/python3.6|/usr/bin/env python3.6|g' $SNAPCRAFT_PART_INSTALL/bin/idle3.6
      sed -i 's|/bin/python3.6|/usr/bin/env python3.6|g' $SNAPCRAFT_PART_INSTALL/bin/easy_install-3.6
      sed -i 's|/bin/python3.6|/usr/bin/env python3.6|g' $SNAPCRAFT_PART_INSTALL/bin/2to3-3.6
    build-packages:
    - zlib1g-dev
    - libffi-dev
    - libssl-dev
    - ca-certificates
    - libsqlite3-dev
    - sqlite3
    - sqlite

environment:
  PYTHONUSERBASE: $SNAP_USER_DATA

apps:
  python:
    command: bin/python3
    plugs: [home, network, network-bind]
  pythonm:
    command: bin/python3.6m
    plugs: [home, network, network-bind]
  pip:
    command: bin/pip3
    plugs: [home, network, network-bind]
  pydoc:
    command: bin/pydoc3
    plugs: [home]
  python-config:
    command: bin/python3-config
  pyvenv:
    command: bin/pyvenv
    plugs: [home]
  idle:
    command: bin/idle3.6
    plugs: [home]
  easy-install:
    command: bin/easy_install-3.6
    plugs: [home, network]
  2to3:
    command: bin/2to3-3.6
    plugs: [home]
